# apiVersion: v1
# kind: Namespace
# metadata:
#   labels:
#     app.kubernetes.io/component: projectset-app
#     app.kubernetes.io/name: namespace
#     app.kubernetes.io/part-of: projectset-app
#   name: projectset-app-system
# ---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: projectset-app
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: projectset-app
  name: projectset-app-service
  namespace: projectset-app-system
spec:
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: http
  selector:
    name: projectset-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: projectset-app
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: projectset-app
    name: projectset-app
  name: projectset-app
  namespace: projectset-app-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: projectset-app
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: projectset-app
      labels:
        name: projectset-app
    spec:
      containers:
      - image: migrx/projectset-app:0.1.0
        imagePullPolicy: Always
        name: projectset-app
        env:
        - name: APP_CONF
          value: "/app/secret/app.yaml"
        - name: LOGLEVEL
          value: DEBUG
        - name: GIT_EMAIL
          value: "projectset-app@migrx.io"
        - name: GIT_USER
          value: "projectset-app"
        ports:
        - containerPort: 8082
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 512Mi

        volumeMounts:
          - mountPath: "/app/secret"
            name: app-conf
            readOnly: true

      volumes:
        - name: app-conf
          secret:
            secretName: app-conf
